# -*- coding: utf-8 -*-
"""Codice_PL_1104.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Xb8R1vBu5zskm-fzcEeEX-dqRHbR-3M
"""

# ============================================================
# CODE CELL 1A - IMPORT
# ============================================================

import math
import re
from copy import deepcopy
from collections import defaultdict
from functools import lru_cache

import numpy as np
import pandas as pd

from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill

# =========================
# CODE CELL 1B - READ EXCEL
# =========================

# After the upload, use the correct path
INPUT_XLSX = "/content/PL_1004.xlsx"
OUTPUT_XLSX = "/content/PL_1004_pronto_intervento_output.xlsx"

xls = pd.ExcelFile(INPUT_XLSX)

pl_df = pd.read_excel(xls, "PL")
orario_df = pd.read_excel(xls, "Orario")

pl_df.columns = [str(c).strip() for c in pl_df.columns]
orario_df.columns = [str(c).strip() for c in orario_df.columns]

# colonne chiave
id_col = [c for c in pl_df.columns if "WBS" in c][0]
dur_col = [c for c in pl_df.columns if "h arrot" in c][0]

pl_df["task_id"] = pd.to_numeric(pl_df[id_col], errors="coerce").astype(int)
pl_df["duration_hours"] = pd.to_numeric(pl_df[dur_col], errors="coerce").astype(int)

pl_df["Elemento"] = pl_df["Elemento"].astype(str).str.strip()
pl_df["Nome attività"] = pl_df["Nome attività"].astype(str).str.strip()
pl_df["full_name"] = pl_df["Elemento"] + " - " + pl_df["Nome attività"]

print("PL:", pl_df.shape)
print("Orario:", orario_df.shape)
display(pl_df.head())

# =========================
# CODE CELL 1C - RISK LIBRARY
# =========================

RISK_LIBRARY = {

    "Rain": {
        "ID Rischio": "R1",
        "Evento": "Rain",
        "Tipo impatto": "Blocco totale",
        "Risorse colpite": "Tutte",
        "Recupero possibile?": "SI",
    },

    "High Wind": {
        "ID Rischio": "R2",
        "Evento": "High Wind",
        "Tipo impatto": "Blocco totale",
        "Risorse colpite": "Gru",
        "Recupero possibile?": "SI",
    },

    "Concrete Pump Failure": {
        "ID Rischio": "R3",
        "Evento": "Concrete Pump Failure",
        "Tipo impatto": "Blocco totale",
        "Risorse colpite": "Pompa Calcestruzzo",
        "Recupero possibile?": "SI",
    },


}

print("Libreria rischi caricata.")
print("Rischi disponibili:")
print(list(RISK_LIBRARY.keys()))

# =========================
# CODE CELL 1D - RISK EVENT UI
# =========================

import ipywidgets as widgets
from IPython.display import display, clear_output

# -------------------------
# GLOBAL RISK LIST
# -------------------------

IMPREVISTI_INPUT = []

# -------------------------
# AVAILABLE HOURS
# -------------------------

AVAILABLE_HOURS = sorted(
    orario_df["Ora"].astype(str).unique().tolist()
)

# -------------------------
# WIDGETS
# -------------------------

risk_dropdown = widgets.Dropdown(
    options=list(RISK_LIBRARY.keys()),
    description="Risk event:",
    layout=widgets.Layout(width="400px")
)

start_date_picker = widgets.DatePicker(
    description="Start date:"
)

start_hour_dropdown = widgets.Dropdown(
    options=AVAILABLE_HOURS,
    description="Start time:"
)

end_date_picker = widgets.DatePicker(
    description="End date:"
)

end_hour_dropdown = widgets.Dropdown(
    options=AVAILABLE_HOURS,
    description="End time:"
)

add_button = widgets.Button(
    description="Add risk event",
    button_style="warning",
    icon="plus"
)

run_button = widgets.Button(
    description="Run simulation",
    button_style="success",
    icon="play"
)

clear_button = widgets.Button(
    description="Clear risks",
    button_style="danger",
    icon="trash"
)

output_table = widgets.Output()

# -------------------------
# ADD RISK CALLBACK
# -------------------------

def add_risk_callback(b):

    risk_name = risk_dropdown.value
    risk_data = RISK_LIBRARY[risk_name].copy()

    risk_data["Data inizio"] = str(start_date_picker.value)
    risk_data["Data fine"] = str(end_date_picker.value)

    risk_data["Ora inizio"] = start_hour_dropdown.value
    risk_data["Ora fine"] = end_hour_dropdown.value

    IMPREVISTI_INPUT.append(risk_data)

    with output_table:
        clear_output(wait=True)

        df = pd.DataFrame(IMPREVISTI_INPUT)

        print("Added risk events:")
        display(df)

# -------------------------
# CLEAR CALLBACK
# -------------------------

def clear_callback(b):

    IMPREVISTI_INPUT.clear()

    with output_table:
        clear_output(wait=True)

        print("Risk list cleared.")

# -------------------------
# BUILD DF FUNCTION
# -------------------------

def build_imprevisti_df():

    df = pd.DataFrame(IMPREVISTI_INPUT)

    if not df.empty:
        df.columns = [str(c).strip() for c in df.columns]

    return df

# -------------------------
# BUTTON EVENTS
# -------------------------

add_button.on_click(add_risk_callback)
clear_button.on_click(clear_callback)

# -------------------------
# LAYOUT
# -------------------------

title = widgets.HTML(
    value="""
    <h2 style='color:#1F4E78'>
    Construction Risk Simulation Tool
    </h2>
    """
)

subtitle = widgets.HTML(
    value="""
    <b>Insert risk events and run the simulation.</b>
    """
)

ui = widgets.VBox([

    title,
    subtitle,

    widgets.HTML("<hr>"),

    risk_dropdown,

    widgets.HBox([
        start_date_picker,
        start_hour_dropdown
    ]),

    widgets.HBox([
        end_date_picker,
        end_hour_dropdown
    ]),

    widgets.HBox([
        add_button,
        clear_button,
        run_button
    ]),

    widgets.HTML("<hr>"),

    output_table

])

display(ui)

# =========================
# CODE CELL 1E - CONFIG TEAM RECOVERY
# =========================

ORE_GIORNO = 8

# -------------------------
# WORKERS'HOURLY COST
# -------------------------

COSTI_OPERAI_ORARI = {
    "Operai Liv.1": 26,
    "Operai Liv.2": 29,
    "Operai Liv.3": 31,
}

# -------------------------
# MACHINES COST
# -------------------------

COSTI_MACCHINARI = {
    "Gru": {
        "tipo_costo": "giornaliero",
        "costo": 300,
    },
    "Pompa Calcestruzzo": {
        "tipo_costo": "orario",
        "costo": 210,
    },
    "Escavatore": {
        "tipo_costo": "orario",
        "costo": 0,
    },
    "Autocarro": {
        "tipo_costo": "orario",
        "costo": 0,
    },
}

# -------------------------
# TEAM MULTIPLIER LOGIC
# -------------------------

# Recovery can increase by a maximum of +1 team
# compared to the baseline multiplier of the single activity.
MAX_EXTRA_TEAMS_PER_TASK = 1

RECOVERABLE_ACTIVITIES = {
    "Armatura",
    "Getto",
    "Posa",
    "Casseratura Orizzontale",
    "Casseratura Verticale",
    "Scasseratura Orizzontale",
    "Scasseratura Verticale",
}

NON_RECOVERABLE_ACTIVITIES = {
    "Presa",
}

# Min Duration to apply recovery
MIN_TASK_DURATION_FOR_COMPRESSION = 2

# Minimum remaining duration allowed
# 0.50 = you cannot go below 50% of the baseline duration
MIN_DURATION_RATIO = 0.50

# -------------------------
# MACHINERY SCALING RULES
# -------------------------
# always:
# if the machine is YES in the PL, it immediately scales with the multiplier.
#
# after_first_extra_team:
# at the first team increase, only the workers increase.
# from the second increase onwards, the machinery also increases.
#
# never:
# machinery never scales in recovery.

MACHINE_SCALE_RULES = {
    "Getto": "always",
    "Posa": "always",

    "Armatura": "after_first_extra_team",
    "Casseratura Orizzontale": "after_first_extra_team",
    "Casseratura Verticale": "after_first_extra_team",
    "Scasseratura Orizzontale": "after_first_extra_team",
    "Scasseratura Verticale": "after_first_extra_team",

    "Presa": "never",
}

print("Config recovery caricata.")
print("Max extra team per task:", MAX_EXTRA_TEAMS_PER_TASK)
print("Costi operai:", COSTI_OPERAI_ORARI)
print("Costi macchinari:", COSTI_MACCHINARI)
print("Regole scaling macchinari:", MACHINE_SCALE_RULES)

# =========================
# CODE CELL 1F - CONFIG RESOURCES
# =========================

LABOR_COLS = [
    "Operai Liv.1",
    "Operai Liv.2",
    "Operai Liv.3",
]

MACHINE_COLS = [
    "Gru",
    "Pompa Calcestruzzo",
    "Escavatore",
    "Autocarro",
]

RESOURCE_COLS = LABOR_COLS + MACHINE_COLS

ALL_RESOURCES_LABELS = {
    "Tutte",
    "TUTTE",
    "ALL",
    "All",
}

print("Labor cols:")
print(LABOR_COLS)

print("\nMachine cols:")
print(MACHINE_COLS)

print("\nResource cols:")
print(RESOURCE_COLS)

# =========================
# CODE CELL 1G - CALENDAR CONFIG
# =========================

ORE_GIORNO = 8

EXTRA_BUSINESS_DAYS = 60

print("Ore giorno:", ORE_GIORNO)
print("Extra business days:", EXTRA_BUSINESS_DAYS)

# =========================
# CODE CELL 1H - FLAG SIMULATION
# =========================

ENABLE_RECOVERY = True

RECOVERY_START_MODE = "risk_start"

print("Recovery enabled:", ENABLE_RECOVERY)
print("Recovery start mode:", RECOVERY_START_MODE)

# =========================
# CODE CELL 2 - DATA PREPARATION
# =========================

pl_df.columns = [str(c).strip() for c in pl_df.columns]
orario_df.columns = [str(c).strip() for c in orario_df.columns]

print("Input pronti.")

print("PL columns:")
print(pl_df.columns.tolist())

print("\nOrario columns:")
print(orario_df.columns.tolist())

print(LABOR_COLS)
print(RESOURCE_COLS)

# =========================
# CODE CELL 3 - MODEL FUNCTIONS
# =========================

def parse_predecessors(x):
    if pd.isna(x):
        return []
    parts = re.split(r"[;,]+", str(x))
    return [int(p.strip()) for p in parts if p.strip().isdigit()]


def parse_id_list(x):
    if pd.isna(x):
        return []
    parts = re.split(r"[;,]+", str(x))
    return [int(p.strip()) for p in parts if p.strip().isdigit()]


def normalize_yes_no(v):
    return str(v).strip().upper() == "SI"


def clone_tasks(tasks):
    return deepcopy(tasks)


def normalize_hour_label(s):
    s = str(s).strip()
    m = re.match(r"^\s*(\d{1,2}):(\d{2})-(\d{1,2}):(\d{2})\s*$", s)
    if not m:
        return s
    h1, m1, h2, m2 = m.groups()
    return f"{int(h1):02d}:{m1}-{int(h2):02d}:{m2}"


def build_tasks(pl_df):
    pl = pl_df.copy()

    pl["task_id"] = pd.to_numeric(pl["task_id"], errors="coerce").astype(int)
    pl["duration_hours"] = pd.to_numeric(pl["duration_hours"], errors="coerce").fillna(0).astype(int)
    pl["Ora assoluta Inizio"] = pd.to_numeric(pl["Ora assoluta Inizio"], errors="coerce").astype(int)
    pl["Ora assoluta Fine"] = pd.to_numeric(pl["Ora assoluta Fine"], errors="coerce").astype(int)
    pl["Predecessori"] = pl["Predecessori"].apply(parse_predecessors)

    if "Moltiplicatore risorse" not in pl.columns:
        raise ValueError("Manca la colonna 'Moltiplicatore risorse' nel foglio PL.")

    pl["Moltiplicatore risorse"] = pd.to_numeric(
        pl["Moltiplicatore risorse"],
        errors="coerce"
    ).fillna(1).astype(float)

    for c in LABOR_COLS:
        pl[c] = pd.to_numeric(pl[c], errors="coerce").fillna(0.0)

    # save the YES/NO machine flags
    for c in MACHINE_COLS:
        pl[f"{c}_flag"] = pl[c].apply(normalize_yes_no)

    # YES => Machine quantity = Resource multiplier
    # NO => 0
    for c in MACHINE_COLS:
        pl[c] = pl.apply(
            lambda row: float(row["Moltiplicatore risorse"]) if row[f"{c}_flag"] else 0.0,
            axis=1
        )

    succ = defaultdict(list)
    dur_map = pl.set_index("task_id")["duration_hours"].to_dict()

    for _, row in pl.iterrows():
        for p in row["Predecessori"]:
            succ[p].append(int(row["task_id"]))

    @lru_cache(None)
    def critical_tail(task_id):
        if task_id not in succ or len(succ[task_id]) == 0:
            return dur_map[task_id]
        return dur_map[task_id] + max(critical_tail(s) for s in succ[task_id])

    tasks = {}

    for _, row in pl.iterrows():
        tid = int(row["task_id"])
        base_demand = {c: float(row[c]) for c in RESOURCE_COLS}

        machine_flags = {
            c: bool(row[f"{c}_flag"])
            for c in MACHINE_COLS
        }

        tasks[tid] = {
            "id": tid,
            "name": str(row["Nome attività"]).strip(),
            "full_name": str(row["full_name"]).strip(),
            "elemento": str(row["Elemento"]).strip(),

            "duration": int(row["duration_hours"]),
            "base_cost": float(row["Costo"]),

            "baseline_multiplier": float(row["Moltiplicatore risorse"]),
            "recovery_multiplier": float(row["Moltiplicatore risorse"]),

            "base_start": int(row["Ora assoluta Inizio"]),
            "base_finish": int(row["Ora assoluta Fine"]),
            "preds": list(row["Predecessori"]),
            "criticality": float(critical_tail(tid)),

            "machine_flags": machine_flags,

            "base_demand": base_demand,
            "effective_duration": int(row["duration_hours"]),
            "effective_demand": dict(base_demand),

            "remaining": int(row["duration_hours"]),
            "start": None,
            "finish": None,
            "assigned_hours": [],
        }

    return pl, tasks


def build_extended_calendar(orario_df, extra_business_days=10):
    cal = orario_df[["Data", "Ora", "Ora Assoluta"]].copy()
    cal["Data"] = pd.to_datetime(cal["Data"]).dt.normalize()
    cal["Ora"] = cal["Ora"].apply(normalize_hour_label)
    cal["Ora Assoluta"] = pd.to_numeric(cal["Ora Assoluta"], errors="coerce").astype(int)

    cal = cal.drop_duplicates("Ora Assoluta").sort_values("Ora Assoluta").reset_index(drop=True)

    first_day = cal["Data"].min()
    day_pattern = cal.loc[cal["Data"] == first_day, "Ora"].astype(str).tolist()

    last_abs = int(cal["Ora Assoluta"].max())
    last_date = pd.Timestamp(cal["Data"].max())

    extra_rows = []
    current_abs = last_abs
    current_date = last_date

    for _ in range(extra_business_days):
        current_date = pd.Timestamp(current_date) + pd.tseries.offsets.BDay(1)
        for hour_label in day_pattern:
            current_abs += 1
            extra_rows.append({
                "Data": pd.Timestamp(current_date).normalize(),
                "Ora": str(hour_label),
                "Ora Assoluta": current_abs
            })

    if extra_rows:
        cal = pd.concat([cal, pd.DataFrame(extra_rows)], ignore_index=True)

    cal = cal.sort_values("Ora Assoluta").reset_index(drop=True)
    return cal


def compute_original_peak_capacities(orario_df, pl_clean, id_col):
    task_res = pl_clean.set_index("task_id")[RESOURCE_COLS]
    rows = []

    for _, row in orario_df[["Ora Assoluta", id_col]].iterrows():
        ids = parse_id_list(row[id_col])

        if ids:
            ser = task_res.loc[ids].sum()
        else:
            ser = pd.Series({c: 0.0 for c in RESOURCE_COLS})

        ser["Ora Assoluta"] = int(row["Ora Assoluta"])
        rows.append(ser)

    usage_df = pd.DataFrame(rows).fillna(0.0)
    return usage_df[RESOURCE_COLS].max().to_dict()


def preprocess_imprevisti(imprevisti_df):
    imp = imprevisti_df.copy()
    imp["Data inizio"] = pd.to_datetime(imp["Data inizio"]).dt.normalize()
    imp["Data fine"] = pd.to_datetime(imp["Data fine"]).dt.normalize()
    imp["Ora inizio"] = imp["Ora inizio"].apply(normalize_hour_label)
    imp["Ora fine"] = imp["Ora fine"].apply(normalize_hour_label)
    imp["Tipo impatto"] = imp["Tipo impatto"].astype(str).str.strip()
    imp["Risorse colpite"] = imp["Risorse colpite"].astype(str).str.strip()
    imp["Recupero possibile?"] = imp["Recupero possibile?"].astype(str).str.strip().str.upper()

    if "Intensità" not in imp.columns:
        imp["Intensità"] = np.nan

    imp["Intensità"] = pd.to_numeric(imp["Intensità"], errors="coerce")
    imp["Intensità"] = np.where(
        imp["Tipo impatto"].str.upper().eq("BLOCCO TOTALE"),
        1.0,
        imp["Intensità"]
    )
    imp["Intensità"] = pd.to_numeric(imp["Intensità"], errors="coerce").fillna(1.0).clip(0, 1)

    return imp


def make_calendar_key_map(calendar_df):
    return {
        (row["Data"], str(row["Ora"]).strip()): int(row["Ora Assoluta"])
        for _, row in calendar_df.iterrows()
    }


def build_capacity_table_from_imprevisti(calendar_df, peak_caps, imprevisti_df):
    capacities = calendar_df.copy()
    capacities["Data"] = pd.to_datetime(capacities["Data"]).dt.normalize()
    capacities["Ora"] = capacities["Ora"].apply(normalize_hour_label)

    for r, cap in peak_caps.items():
        capacities[r] = float(cap)

    log_rows = []

    for _, imp in imprevisti_df.iterrows():

        start_date = pd.Timestamp(imp["Data inizio"]).normalize()
        end_date = pd.Timestamp(imp["Data fine"]).normalize()

        start_hour = normalize_hour_label(imp["Ora inizio"])
        end_hour = normalize_hour_label(imp["Ora fine"])

        tipo = str(imp["Tipo impatto"]).strip().upper()
        intensity = float(imp["Intensità"])

        raw_res = str(imp["Risorse colpite"]).strip()

        if raw_res in ALL_RESOURCES_LABELS:
            target_resources = list(RESOURCE_COLS)
        else:
            target_resources = [x.strip() for x in re.split(r"[;,]+", raw_res) if x.strip()]

        # days present in the calendar within the unexpected range
        valid_days = sorted(
            capacities.loc[
                (capacities["Data"] >= start_date) &
                (capacities["Data"] <= end_date),
                "Data"
            ].drop_duplicates()
        )

        if len(valid_days) == 0:
            raise ValueError(
                f"Nessun giorno calendario trovato per imprevisto {imp['ID Rischio']} "
                f"tra {start_date.date()} e {end_date.date()}"
            )

        for day in valid_days:

            day_rows = capacities[capacities["Data"] == day].copy()

            if start_hour not in set(day_rows["Ora"]):
                raise ValueError(
                    f"Ora inizio {start_hour} non trovata nel calendario per il giorno {day.date()}"
                )

            if end_hour not in set(day_rows["Ora"]):
                raise ValueError(
                    f"Ora fine {end_hour} non trovata nel calendario per il giorno {day.date()}"
                )

            start_abs = int(day_rows.loc[day_rows["Ora"] == start_hour, "Ora Assoluta"].iloc[0])
            end_abs = int(day_rows.loc[day_rows["Ora"] == end_hour, "Ora Assoluta"].iloc[0])

            if end_abs < start_abs:
                raise ValueError(
                    f"Imprevisto {imp['ID Rischio']} ha end_abs < start_abs nel giorno {day.date()}"
                )

            for r in target_resources:
                if r not in capacities.columns:
                    print(f"Attenzione: risorsa '{r}' non trovata. Salto.")
                    continue

                mask = (
                    (capacities["Ora Assoluta"] >= start_abs) &
                    (capacities["Ora Assoluta"] <= end_abs)
                )

                before = capacities.loc[mask, r].copy()

                if tipo == "BLOCCO TOTALE":
                    capacities.loc[mask, r] = 0.0
                else:
                    capacities.loc[mask, r] = capacities.loc[mask, r] * (1.0 - intensity)

                after = capacities.loc[mask, r]

                log_rows.append({
                    "ID Rischio": imp["ID Rischio"],
                    "Evento": imp["Evento"],
                    "Data": day,
                    "Risorsa": r,
                    "Start abs": start_abs,
                    "End abs": end_abs,
                    "Ore impattate": end_abs - start_abs + 1,
                    "Cap media prima": float(before.mean()) if len(before) else np.nan,
                    "Cap media dopo": float(after.mean()) if len(after) else np.nan,
                    "Recupero possibile?": imp["Recupero possibile?"]
                })

    return capacities, pd.DataFrame(log_rows)

def identify_impacted_tasks(tasks, capacities_df):
    cap = capacities_df.set_index("Ora Assoluta")
    rows = []

    for tid, task in tasks.items():
        demanded = {r: v for r, v in task["base_demand"].items() if float(v) > 0}
        impacted = False
        impacted_hours = 0
        impacted_resources = set()

        for h in range(int(task["base_start"]), int(task["base_finish"]) + 1):
            if h not in cap.index:
                continue

            for r, demand in demanded.items():
                avail = float(cap.at[h, r])

                if avail + 1e-9 < float(demand):
                    impacted = True
                    impacted_hours += 1
                    impacted_resources.add(r)

        rows.append({
            "task_id": tid,
            "full_name": task["full_name"],
            "Task colpita?": "SI" if impacted else "NO",
            "Ore potenzialmente critiche": impacted_hours,
            "Risorse critiche": ", ".join(sorted(impacted_resources)),
            "Criticality": task["criticality"]
        })

    out = pd.DataFrame(rows)
    out = out.sort_values(
        ["Task colpita?", "Ore potenzialmente critiche", "Criticality"],
        ascending=[False, False, False]
    ).reset_index(drop=True)

    return out


def build_successor_map(tasks):
    succ = defaultdict(list)

    for tid, task in tasks.items():
        for p in task["preds"]:
            succ[p].append(tid)

    return succ


def get_indirectly_impacted_tasks(tasks, direct_impacted_ids):
    succ = build_successor_map(tasks)

    indirect = set()
    frontier = list(direct_impacted_ids)

    while frontier:
        current = frontier.pop()

        for s in succ.get(current, []):
            if s not in direct_impacted_ids and s not in indirect:
                indirect.add(s)
                frontier.append(s)

    return indirect


def schedule_tasks(tasks, capacities_df, allow_early_start=False):
    cap = capacities_df.copy().sort_values("Ora Assoluta").set_index("Ora Assoluta")
    cal_hours = list(cap.index)

    for task in tasks.values():
        task["remaining"] = int(task["effective_duration"])
        task["start"] = None
        task["finish"] = None
        task["assigned_hours"] = []

    hourly_rows = []
    blocked_rows = []

    task_ids_sorted = sorted(
        tasks.keys(),
        key=lambda tid: (-tasks[tid]["criticality"], tasks[tid]["base_start"], tid)
    )

    for hour in cal_hours:
        remaining_cap = cap.loc[hour, RESOURCE_COLS].astype(float).to_dict()

        candidates = []

        for tid in task_ids_sorted:
            task = tasks[tid]

            if task["remaining"] <= 0:
                continue

            preds_done = all(
                tasks[p]["finish"] is not None and tasks[p]["finish"] < hour
                for p in task["preds"]
            )

            if not preds_done:
                continue

            earliest_by_preds = max([tasks[p]["finish"] for p in task["preds"]], default=0) + 1
            earliest = earliest_by_preds if allow_early_start else max(task["base_start"], earliest_by_preds)

            if hour >= earliest:
                candidates.append(tid)

        for tid in candidates:
            task = tasks[tid]
            demand = task["effective_demand"]

            feasible = True
            lacking = []

            for r, req in demand.items():
                if float(req) > float(remaining_cap.get(r, 0.0)) + 1e-9:
                    feasible = False
                    lacking.append(r)

            if feasible:
                for r, req in demand.items():
                    remaining_cap[r] -= float(req)

                task["remaining"] -= 1
                task["assigned_hours"].append(hour)

                if task["start"] is None:
                    task["start"] = hour

                task["finish"] = hour

                hourly_rows.append({
                    "Ora Assoluta": hour,
                    "task_id": tid,
                    "full_name": task["full_name"],
                    **{r: float(demand[r]) for r in RESOURCE_COLS}
                })
            else:
                blocked_rows.append({
                    "Ora Assoluta": hour,
                    "task_id": tid,
                    "full_name": task["full_name"],
                    "Motivo": "Capacità insufficiente",
                    "Risorse mancanti": ", ".join(lacking)
                })

    for tid, task in tasks.items():
        if task["remaining"] > 0:
            blocked_rows.append({
                "Ora Assoluta": np.nan,
                "task_id": tid,
                "full_name": task["full_name"],
                "Motivo": "Task non completata",
                "Risorse mancanti": ""
            })

    return pd.DataFrame(hourly_rows), pd.DataFrame(blocked_rows)


def schedule_tasks_no_recovery_locked(tasks, capacities_df):
    cap = capacities_df.copy().sort_values("Ora Assoluta").set_index("Ora Assoluta")

    for task in tasks.values():
        task["effective_duration"] = int(task["duration"])
        task["effective_demand"] = dict(task["base_demand"])
        task["remaining"] = int(task["duration"])
        task["start"] = None
        task["finish"] = None
        task["assigned_hours"] = []
        task["lost_hours"] = 0

    hourly_rows = []
    blocked_rows = []

    task_ids_sorted = sorted(tasks.keys(), key=lambda tid: (tasks[tid]["base_start"], tid))

    for tid in task_ids_sorted:
        task = tasks[tid]

        pred_finish = []

        for p in task["preds"]:
            if p in tasks and tasks[p]["finish"] is not None:
                pred_finish.append(tasks[p]["finish"])

        earliest_by_preds = max(pred_finish, default=0) + 1
        planned_start = max(task["base_start"], earliest_by_preds)

        current_hour = planned_start
        worked_hours = 0

        while worked_hours < int(task["duration"]):

            if current_hour not in cap.index:
                blocked_rows.append({
                    "Ora Assoluta": current_hour,
                    "task_id": tid,
                    "full_name": task["full_name"],
                    "Motivo": "Ora non presente nel calendario",
                    "Risorse mancanti": ""
                })
                current_hour += 1
                continue

            demand = task["base_demand"]
            feasible = True
            lacking = []

            for r, req in demand.items():
                req = float(req)
                available = float(cap.at[current_hour, r])

                if req > available + 1e-9:
                    feasible = False
                    lacking.append(r)

            if feasible:
                if task["start"] is None:
                    task["start"] = current_hour

                task["assigned_hours"].append(current_hour)
                task["finish"] = current_hour
                worked_hours += 1

                hourly_rows.append({
                    "Ora Assoluta": current_hour,
                    "task_id": tid,
                    "full_name": task["full_name"],
                    **{r: float(demand[r]) for r in RESOURCE_COLS}
                })

            else:
                task["lost_hours"] += 1

                blocked_rows.append({
                    "Ora Assoluta": current_hour,
                    "task_id": tid,
                    "full_name": task["full_name"],
                    "Motivo": "Blocco imprevisto / capacità insufficiente",
                    "Risorse mancanti": ", ".join(lacking)
                })

            current_hour += 1

        task["remaining"] = 0

    return pd.DataFrame(hourly_rows), pd.DataFrame(blocked_rows)


def build_pl_rescheduled(pl_clean, tasks, calendar_df):
    out = pl_clean.copy()

    out["Nuova Ora assoluta Inizio"] = out["task_id"].map({tid: t["start"] for tid, t in tasks.items()})
    out["Nuova Ora assoluta Fine"] = out["task_id"].map({tid: t["finish"] for tid, t in tasks.items()})
    out["Durata effettiva (h)"] = out["task_id"].map({tid: t["effective_duration"] for tid, t in tasks.items()})
    out["Moltiplicatore recovery"] = out["task_id"].map({tid: t.get("recovery_multiplier", t["baseline_multiplier"]) for tid, t in tasks.items()})

    out["Ritardo fine (h)"] = (
        pd.to_numeric(out["Nuova Ora assoluta Fine"], errors="coerce")
        - pd.to_numeric(out["Ora assoluta Fine"], errors="coerce")
    ).fillna(0).astype(int)

    out["Ritardo fine (gg lav)"] = (out["Ritardo fine (h)"] / ORE_GIORNO).round(2)

    cal_map = calendar_df.set_index("Ora Assoluta")[["Data", "Ora"]].to_dict("index")

    def map_date(abs_hour):
        if pd.isna(abs_hour):
            return pd.NaT
        return cal_map.get(int(abs_hour), {}).get("Data", pd.NaT)

    def map_hour(abs_hour):
        if pd.isna(abs_hour):
            return None
        return cal_map.get(int(abs_hour), {}).get("Ora", None)

    out["Nuova Data Inizio"] = out["Nuova Ora assoluta Inizio"].apply(map_date)
    out["Nuova Ora Inizio"] = out["Nuova Ora assoluta Inizio"].apply(map_hour)
    out["Nuova Data Fine"] = out["Nuova Ora assoluta Fine"].apply(map_date)
    out["Nuova Ora Fine"] = out["Nuova Ora assoluta Fine"].apply(map_hour)

    return out


def build_orario_rescheduled(orario_df, hourly_df, id_col):
    out = orario_df.copy()

    if hourly_df.empty:
        out[id_col] = ""
        return out

    alloc = (
        hourly_df.groupby("Ora Assoluta")
        .agg({
            "task_id": lambda s: ";".join(str(int(x)) for x in sorted(s))
        })
        .reset_index()
    )

    alloc_map = dict(zip(alloc["Ora Assoluta"], alloc["task_id"]))
    out[id_col] = out["Ora Assoluta"].map(alloc_map).fillna("")

    return out


def build_delayed_tasks_report(pl_res):
    cols = [
        "task_id",
        "Elemento",
        "Nome attività",
        "full_name",
        "Ora assoluta Inizio",
        "Ora assoluta Fine",
        "Nuova Ora assoluta Inizio",
        "Nuova Ora assoluta Fine",
        "Ritardo fine (h)",
        "Ritardo fine (gg lav)",
        "Predecessori"
    ]

    out = pl_res[cols].copy()
    out = out[out["Ritardo fine (h)"] > 0].copy()
    out = out.sort_values(["Ritardo fine (h)", "Nuova Ora assoluta Fine"], ascending=[False, True]).reset_index(drop=True)

    return out


def calculate_recovery_candidate(task, impact_type):
    if task["name"] not in RECOVERABLE_ACTIVITIES:
        return None

    if int(task["duration"]) < MIN_TASK_DURATION_FOR_COMPRESSION:
        return None

    baseline_multiplier = float(task["baseline_multiplier"])
    recovery_multiplier = baseline_multiplier + MAX_EXTRA_TEAMS_PER_TASK
    extra_teams = recovery_multiplier - baseline_multiplier

    base_duration = int(task["duration"])

    proposed_duration = int(math.ceil(
        base_duration * (baseline_multiplier / recovery_multiplier)
    ))

    min_allowed_duration = int(math.ceil(base_duration * MIN_DURATION_RATIO))
    proposed_duration = max(proposed_duration, min_allowed_duration)

    if proposed_duration >= base_duration:
        return None

    new_demand = {}

    ratio = recovery_multiplier / baseline_multiplier

    # Workers: always change with the multiplier
Translated with https://laratranslate.com
    for r in LABOR_COLS:
        new_demand[r] = round(float(task["base_demand"][r]) * ratio, 2)

    # Machines: change according to activity rule
    machine_rule = MACHINE_SCALE_RULES.get(task["name"], "never")

    for r in MACHINE_COLS:
        base_machine_qty = float(task["base_demand"].get(r, 0.0))

        if not task["machine_flags"].get(r, False):
            new_demand[r] = 0.0
            continue

        if machine_rule == "always":
            # Getto / Posa (Casting / Slab placement):
            # machinery scales immediately with the team multiplier
            new_demand[r] = recovery_multiplier

        elif machine_rule == "after_first_extra_team":
            # Armatura / Casseratura (Reinforcement / Formwork):
            # first increase: workers only
            # from the second increase onward: workers + machinery
            if extra_teams <= 1:
                new_demand[r] = base_machine_qty
            else:
                new_demand[r] = recovery_multiplier

        else:
            # never
            new_demand[r] = base_machine_qty

    extra_demand = {
        r: max(0.0, float(new_demand[r]) - float(task["base_demand"][r]))
        for r in RESOURCE_COLS
    }

    recovery_hours = proposed_duration
    total_extra_cost = 0.0
    extra_cost_cols = {}

    # Costi operai
    for r in LABOR_COLS:
        extra_qty = float(extra_demand.get(r, 0.0))
        cost_r = extra_qty * COSTI_OPERAI_ORARI.get(r, 0) * recovery_hours
        extra_cost_cols[f"Costo extra {r}"] = cost_r
        total_extra_cost += cost_r

    # Costi macchinari
    for r in MACHINE_COLS:
        extra_qty = float(extra_demand.get(r, 0.0))

        if extra_qty <= 0:
            cost_r = 0.0
        else:
            cfg = COSTI_MACCHINARI.get(r, {"tipo_costo": "orario", "costo": 0})

            if cfg["tipo_costo"] == "giornaliero":
                giorni = math.ceil(recovery_hours / ORE_GIORNO)
                cost_r = extra_qty * cfg["costo"] * giorni
            else:
                cost_r = extra_qty * cfg["costo"] * recovery_hours

        extra_cost_cols[f"Costo extra {r}"] = cost_r
        total_extra_cost += cost_r

    base_cost = float(task["base_cost"])
    recovered_hours = base_duration - proposed_duration

    return {
        "task_id": task["id"],
        "full_name": task["full_name"],
        "Tipo impatto recovery": impact_type,
        "Regola macchinari": machine_rule,

        "Baseline multiplier": baseline_multiplier,
        "Recovery multiplier": recovery_multiplier,
        "Extra teams": extra_teams,

        "Durata baseline": base_duration,
        "Durata recovery": proposed_duration,
        "Ore recovery": proposed_duration,
        "Ore recuperate": recovered_hours,

        "Costo attività": base_cost,

        **{f"Extra {r}": extra_demand[r] for r in RESOURCE_COLS},
        **extra_cost_cols,

        "Costo extra totale": total_extra_cost,
        "% costo extra totale": total_extra_cost / base_cost if base_cost > 0 else 0.0,
        "Costo per ora recuperata": total_extra_cost / recovered_hours if recovered_hours > 0 else np.inf,

        "Criticality": task["criticality"],

        "_effective_duration": proposed_duration,
        "_effective_demand": new_demand,
        "_recovery_multiplier": recovery_multiplier,
    }

def apply_recovery_to_task(tasks, candidate_row):
    tid = int(candidate_row["task_id"])
    task = tasks[tid]

    task["effective_duration"] = int(candidate_row["_effective_duration"])
    task["effective_demand"] = dict(candidate_row["_effective_demand"])
    task["recovery_multiplier"] = float(candidate_row["_recovery_multiplier"])


def propose_recovery_plan(tasks, task_colpite_df, imprevisti_df, target_recovery_hours=None):
    direct_ids = set(
        task_colpite_df.loc[
            task_colpite_df["Task colpita?"] == "SI",
            "task_id"
        ].tolist()
    )

    candidates = []

    for tid in direct_ids:
        cand = calculate_recovery_candidate(tasks[tid], "Diretta")
        if cand is not None:
            candidates.append(cand)

    candidates_df = pd.DataFrame(candidates)

    if candidates_df.empty:
        return pd.DataFrame()

    candidates_df = candidates_df.sort_values(
        ["Criticality", "Ore recuperate", "Costo per ora recuperata"],
        ascending=[False, False, True]
    ).reset_index(drop=True)

    plan_rows = []
    recovered_total = 0

    for _, row in candidates_df.iterrows():
        apply_recovery_to_task(tasks, row)
        plan_rows.append(row.drop(labels=[c for c in row.index if str(c).startswith("_")]).to_dict())
        recovered_total += float(row["Ore recuperate"])

        if target_recovery_hours is not None and recovered_total >= target_recovery_hours:
            break

    return pd.DataFrame(plan_rows)


def propose_recovery_plan_economic_chain(tasks, task_colpite_df, imprevisti_df, target_recovery_hours=None):
    direct_ids = set(
        task_colpite_df.loc[
            task_colpite_df["Task colpita?"] == "SI",
            "task_id"
        ].tolist()
    )

    indirect_ids = get_indirectly_impacted_tasks(tasks, direct_ids)
    all_ids = list(direct_ids.union(indirect_ids))

    candidates = []

    for tid in all_ids:
        impact_type = "Diretta" if tid in direct_ids else "Indiretta"
        cand = calculate_recovery_candidate(tasks[tid], impact_type)

        if cand is not None:
            candidates.append(cand)

    candidates_df = pd.DataFrame(candidates)

    if candidates_df.empty:
        return pd.DataFrame(), candidates_df

    candidates_df = candidates_df.sort_values(
        ["Costo per ora recuperata", "Criticality", "Ore recuperate"],
        ascending=[True, False, False]
    ).reset_index(drop=True)

    plan_rows = []
    recovered_total = 0

    for _, row in candidates_df.iterrows():
        apply_recovery_to_task(tasks, row)
        plan_rows.append(row.drop(labels=[c for c in row.index if str(c).startswith("_")]).to_dict())
        recovered_total += float(row["Ore recuperate"])

        if target_recovery_hours is not None and recovered_total >= target_recovery_hours:
            break

    return pd.DataFrame(plan_rows), candidates_df.drop(columns=[c for c in candidates_df.columns if str(c).startswith("_")])


def style_output_excel(filepath):
    wb = load_workbook(filepath)

    header_fill = PatternFill(fill_type="solid", fgColor="1F4E78")
    header_font = Font(color="FFFFFF", bold=True)

    for ws in wb.worksheets:
        for cell in ws[1]:
            cell.fill = header_fill
            cell.font = header_font

        for col_cells in ws.columns:
            max_len = 0
            col_letter = col_cells[0].column_letter

            for cell in col_cells:
                try:
                    val = "" if cell.value is None else str(cell.value)
                    max_len = max(max_len, len(val))
                except:
                    pass

            ws.column_dimensions[col_letter].width = min(max(max_len + 2, 12), 45)

        ws.freeze_panes = "A2"

    wb.save(filepath)

pl_clean, tasks = build_tasks(pl_df)

display(pl_clean[
    [
        "task_id",
        "Nome attività",
        "Moltiplicatore risorse",
        "Operai Liv.1",
        "Operai Liv.2",
        "Operai Liv.3",
        "Gru",
        "Pompa Calcestruzzo",
        "Escavatore",
        "Autocarro"
    ]
].head(10))

# =========================
# CODE CELL 4 - EXECUTION
# =========================

pl_clean, tasks = build_tasks(pl_df)

calendar_df = build_extended_calendar(
    orario_df,
    extra_business_days=EXTRA_BUSINESS_DAYS
)

peak_caps = compute_original_peak_capacities(
    orario_df,
    pl_clean,
    id_col
)

# =========================
# RISKS FROM UI
# =========================

imprevisti_df = build_imprevisti_df()

if imprevisti_df.empty:
    raise ValueError(
        "Nessun imprevisto inserito. "
        "Usa la UI e clicca 'Aggiungi imprevisto' prima di eseguire la Cella 4."
    )

print("===== IMPREVISTI INPUT =====")
display(imprevisti_df)

print("Colonne dataframe:")
print(imprevisti_df.columns.tolist())

imprevisti_clean = preprocess_imprevisti(imprevisti_df)

capacities_df, imprevisti_log_df = build_capacity_table_from_imprevisti(
    calendar_df=calendar_df,
    peak_caps=peak_caps,
    imprevisti_df=imprevisti_clean
)

print("===== LOG IMPREVISTI APPLICATI =====")
display(imprevisti_log_df)


# =========================
# IMPACTED ACTIVITIES
# =========================

task_colpite_df = identify_impacted_tasks(tasks, capacities_df)

attivita_colpite_df = task_colpite_df[
    task_colpite_df["Task colpita?"] == "SI"
].copy()

print("===== ATTIVITÀ DIRETTAMENTE COLPITE DAGLI IMPREVISTI =====")
display(attivita_colpite_df)


# =========================
# SCENARIO 1 - NO RECOVERY
# =========================

tasks_no_recovery = clone_tasks(tasks)

hourly_df, blocked_df = schedule_tasks_no_recovery_locked(
    tasks=tasks_no_recovery,
    capacities_df=capacities_df
)

pl_res = build_pl_rescheduled(
    pl_clean,
    tasks_no_recovery,
    calendar_df
)

orario_res = build_orario_rescheduled(
    orario_df,
    hourly_df,
    id_col
)

delayed_tasks_df = build_delayed_tasks_report(pl_res)

baseline_finish = int(pl_clean["Ora assoluta Fine"].max())
finish_no_recovery = int(pl_res["Nuova Ora assoluta Fine"].max())
delay_no_recovery = finish_no_recovery - baseline_finish

if delay_no_recovery <= 0:
    print("Nessun ritardo finale: recovery non necessaria.")
    ENABLE_RECOVERY_RUN = False
else:
    ENABLE_RECOVERY_RUN = ENABLE_RECOVERY


# =========================
# DEFAULT OUTPUT RECOVERY
# =========================

recovery_plan_df = pd.DataFrame()
capacities_recovery_df = pd.DataFrame()
recovery_log_df = pd.DataFrame()
recovery_start_hour = None
hourly_recovery_df = pd.DataFrame()
blocked_recovery_df = pd.DataFrame()
pl_recovery = pd.DataFrame()
delayed_tasks_recovery_df = pd.DataFrame()
orario_recovery = pd.DataFrame()

recovery_chain_plan_df = pd.DataFrame()
recovery_chain_candidates_df = pd.DataFrame()
capacities_recovery_chain_df = pd.DataFrame()
hourly_recovery_chain_df = pd.DataFrame()
blocked_recovery_chain_df = pd.DataFrame()
pl_recovery_chain = pd.DataFrame()
delayed_tasks_recovery_chain_df = pd.DataFrame()
orario_recovery_chain = pd.DataFrame()

remaining_extra_resources_df = pd.DataFrame()
remaining_extra_resources_chain_df = pd.DataFrame()


# =========================
# SCENARIO 2 - DIRECT RECOVERY
# =========================

if ENABLE_RECOVERY_RUN:

    tasks_recovery = clone_tasks(tasks)

    recovery_plan_df = propose_recovery_plan(
        tasks=tasks_recovery,
        task_colpite_df=task_colpite_df,
        imprevisti_df=imprevisti_clean,
        target_recovery_hours=delay_no_recovery
    )

    capacities_recovery_df = capacities_df.copy()
    recovery_log_df = recovery_plan_df.copy()

    if not imprevisti_log_df.empty:
        recovery_start_hour = int(imprevisti_log_df["Start abs"].min())
    else:
        recovery_start_hour = int(capacities_df["Ora Assoluta"].min())

    hourly_recovery_df, blocked_recovery_df = schedule_tasks(
        tasks=tasks_recovery,
        capacities_df=capacities_recovery_df,
        allow_early_start=False
    )

    pl_recovery = build_pl_rescheduled(
        pl_clean,
        tasks_recovery,
        calendar_df
    )

    delayed_tasks_recovery_df = build_delayed_tasks_report(pl_recovery)

    orario_recovery = build_orario_rescheduled(
        orario_df,
        hourly_recovery_df,
        id_col
    )


    # =========================
    # SCENARIO 3 - (COST-OPTIMIZED) CHAIN RECOVERY
    # =========================

    tasks_recovery_chain = clone_tasks(tasks)

    recovery_chain_plan_df, recovery_chain_candidates_df = propose_recovery_plan_economic_chain(
        tasks=tasks_recovery_chain,
        task_colpite_df=task_colpite_df,
        imprevisti_df=imprevisti_clean,
        target_recovery_hours=delay_no_recovery
    )

    capacities_recovery_chain_df = capacities_df.copy()

    hourly_recovery_chain_df, blocked_recovery_chain_df = schedule_tasks(
        tasks=tasks_recovery_chain,
        capacities_df=capacities_recovery_chain_df,
        allow_early_start=False
    )

    pl_recovery_chain = build_pl_rescheduled(
        pl_clean,
        tasks_recovery_chain,
        calendar_df
    )

    delayed_tasks_recovery_chain_df = build_delayed_tasks_report(pl_recovery_chain)

    orario_recovery_chain = build_orario_rescheduled(
        orario_df,
        hourly_recovery_chain_df,
        id_col
    )


# =========================
# SCENARIO COMPARISON
# =========================

comparison_rows = [
    {
        "Scenario": "Baseline",
        "Fine progetto (ora assoluta)": baseline_finish,
        "Ritardo vs baseline (h)": 0,
        "Ritardo vs baseline (gg lav)": 0.0,
    },
    {
        "Scenario": "Con imprevisti - senza recovery",
        "Fine progetto (ora assoluta)": finish_no_recovery,
        "Ritardo vs baseline (h)": finish_no_recovery - baseline_finish,
        "Ritardo vs baseline (gg lav)": round(
            (finish_no_recovery - baseline_finish) / ORE_GIORNO,
            2
        ),
    }
]

if ENABLE_RECOVERY_RUN and not pl_recovery.empty:
    finish_recovery = int(pl_recovery["Nuova Ora assoluta Fine"].max())

    comparison_rows.append(
        {
            "Scenario": "Con imprevisti + recovery diretta",
            "Fine progetto (ora assoluta)": finish_recovery,
            "Ritardo vs baseline (h)": finish_recovery - baseline_finish,
            "Ritardo vs baseline (gg lav)": round(
                (finish_recovery - baseline_finish) / ORE_GIORNO,
                2
            ),
        }
    )

if ENABLE_RECOVERY_RUN and not pl_recovery_chain.empty:
    finish_recovery_chain = int(pl_recovery_chain["Nuova Ora assoluta Fine"].max())

    comparison_rows.append(
        {
            "Scenario": "Con imprevisti + recovery economica catena",
            "Fine progetto (ora assoluta)": finish_recovery_chain,
            "Ritardo vs baseline (h)": finish_recovery_chain - baseline_finish,
            "Ritardo vs baseline (gg lav)": round(
                (finish_recovery_chain - baseline_finish) / ORE_GIORNO,
                2
            ),
        }
    )

comparison_df = pd.DataFrame(comparison_rows)


# =========================
# PRINT OUTPUT
# =========================

print("Task:", len(tasks))
print("Calendario esteso:", calendar_df.shape)
print("Peak capacities:", peak_caps)
print("Task colpite:", task_colpite_df.shape)
print("Delayed tasks:", delayed_tasks_df.shape)

print("===== CONFRONTO SCENARI =====")
display(comparison_df)

if ENABLE_RECOVERY_RUN:
    print("===== PROPOSTA RECOVERY DIRETTA =====")
    display(recovery_plan_df)

    print("===== CANDIDATE RECOVERY ECONOMICA SU CATENA =====")
    display(recovery_chain_candidates_df)

    print("===== PROPOSTA RECOVERY ECONOMICA SU CATENA =====")
    display(recovery_chain_plan_df)

else:
    print("Recovery non eseguita perché non c'è ritardo finale.")

print(calendar_df["Data"].min())
print(calendar_df["Data"].max())

display(imprevisti_log_df)

# =========================
# CODE CELL 5 - EXPORT
# =========================

def euro_it(x):
    return f"€ {x:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")

def pct_it(x):
    return f"{x:.2%}"


# =========================
# SCENARIO
# =========================

scenario_df = pd.DataFrame([
    {
        "Scenario": "Imprevisti applicati",
        "Recovery attivo": "SI" if ENABLE_RECOVERY else "NO",
        "Recovery eseguita": "SI" if ENABLE_RECOVERY_RUN else "NO",
        "Recovery logica": "Moltiplicatore squadra +1 max",
        "Max extra team per task": MAX_EXTRA_TEAMS_PER_TASK,
        "Min duration ratio": MIN_DURATION_RATIO,
    }
])


# =========================
# COST SUMMARY
# =========================

costo_totale_progetto = float(pl_clean["Costo"].sum())

cost_summary_rows = []

if ENABLE_RECOVERY_RUN and not recovery_plan_df.empty:
    costo_extra_diretto = float(recovery_plan_df["Costo extra totale"].sum())
    costo_attivita_dirette = float(recovery_plan_df["Costo attività"].sum())

    cost_summary_rows.append({
        "Scenario": "Recovery diretta",
        "Costo totale baseline progetto": costo_totale_progetto,
        "Costo attività coinvolte": costo_attivita_dirette,
        "Costo extra totale recovery": costo_extra_diretto,
        "Costo totale progetto con recovery": costo_totale_progetto + costo_extra_diretto,
        "% extra su attività coinvolte": costo_extra_diretto / costo_attivita_dirette if costo_attivita_dirette > 0 else 0,
        "% extra su totale progetto": costo_extra_diretto / costo_totale_progetto if costo_totale_progetto > 0 else 0,
    })

if ENABLE_RECOVERY_RUN and not recovery_chain_plan_df.empty:
    costo_extra_chain = float(recovery_chain_plan_df["Costo extra totale"].sum())
    costo_attivita_chain = float(recovery_chain_plan_df["Costo attività"].sum())

    cost_summary_rows.append({
        "Scenario": "Recovery economica catena",
        "Costo totale baseline progetto": costo_totale_progetto,
        "Costo attività coinvolte": costo_attivita_chain,
        "Costo extra totale recovery": costo_extra_chain,
        "Costo totale progetto con recovery": costo_totale_progetto + costo_extra_chain,
        "% extra su attività coinvolte": costo_extra_chain / costo_attivita_chain if costo_attivita_chain > 0 else 0,
        "% extra su totale progetto": costo_extra_chain / costo_totale_progetto if costo_totale_progetto > 0 else 0,
    })

cost_summary_df = pd.DataFrame(cost_summary_rows)


# =========================
# EXPORT EXCEL
# =========================

with pd.ExcelWriter(OUTPUT_XLSX, engine="openpyxl") as writer:
    # Original
    pl_df.to_excel(writer, sheet_name="PL_originale", index=False)
    orario_df.to_excel(writer, sheet_name="Orario_originale", index=False)

    # Risk and impact
    imprevisti_clean.to_excel(writer, sheet_name="Imprevisti_letti", index=False)
    capacities_df.to_excel(writer, sheet_name="Capacita_imprevisti", index=False)
    imprevisti_log_df.to_excel(writer, sheet_name="Log_imprevisti", index=False)

    task_colpite_df.to_excel(writer, sheet_name="Task_colpite", index=False)
    attivita_colpite_df.to_excel(writer, sheet_name="Attivita_colpite", index=False)

    # No recovery scenario
    blocked_df.to_excel(writer, sheet_name="Task_bloccate", index=False)
    hourly_df.to_excel(writer, sheet_name="Dettaglio_allocazione", index=False)
    pl_res.to_excel(writer, sheet_name="PL_riprogrammato", index=False)
    orario_res.to_excel(writer, sheet_name="Orario_riprogrammato", index=False)
    delayed_tasks_df.to_excel(writer, sheet_name="Report_ritardi", index=False)

    # Comparison
    scenario_df.to_excel(writer, sheet_name="Scenario", index=False)
    comparison_df.to_excel(writer, sheet_name="Confronto_scenari", index=False)
    cost_summary_df.to_excel(writer, sheet_name="Costo_recovery", index=False)

    # Direct Recovery
    if ENABLE_RECOVERY_RUN:
        recovery_plan_df.to_excel(writer, sheet_name="Proposta_recovery_dir", index=False)
        capacities_recovery_df.to_excel(writer, sheet_name="Capacita_recovery_dir", index=False)
        recovery_log_df.to_excel(writer, sheet_name="Recovery_log_dir", index=False)
        hourly_recovery_df.to_excel(writer, sheet_name="Dettaglio_recovery_dir", index=False)
        blocked_recovery_df.to_excel(writer, sheet_name="Task_bloccate_dir", index=False)
        pl_recovery.to_excel(writer, sheet_name="PL_recovery_dir", index=False)
        orario_recovery.to_excel(writer, sheet_name="Orario_recovery_dir", index=False)
        delayed_tasks_recovery_df.to_excel(writer, sheet_name="Report_recovery_dir", index=False)

        # (Cost-optimized) chain recovery
        recovery_chain_candidates_df.to_excel(writer, sheet_name="Candidate_chain", index=False)
        recovery_chain_plan_df.to_excel(writer, sheet_name="Proposta_chain", index=False)
        hourly_recovery_chain_df.to_excel(writer, sheet_name="Dettaglio_chain", index=False)
        blocked_recovery_chain_df.to_excel(writer, sheet_name="Task_bloccate_chain", index=False)
        pl_recovery_chain.to_excel(writer, sheet_name="PL_recovery_chain", index=False)
        orario_recovery_chain.to_excel(writer, sheet_name="Orario_chain", index=False)
        delayed_tasks_recovery_chain_df.to_excel(writer, sheet_name="Report_chain", index=False)

style_output_excel(OUTPUT_XLSX)


# =========================
# PRINT PYTHON
# =========================

print("File creato:", OUTPUT_XLSX)

print("\n===== CONFRONTO SCENARI =====")
display(comparison_df)


# =========================
# COST SUMMARY
# =========================

print("\n===== COSTI RECOVERY - RIEPILOGO =====")

if cost_summary_df.empty:
    print("Nessun costo recovery da stampare.")
else:
    cost_print = cost_summary_df.copy()

    money_cols = [
        "Costo totale baseline progetto",
        "Costo attività coinvolte",
        "Costo extra totale recovery",
        "Costo totale progetto con recovery",
    ]

    pct_cols = [
        "% extra su attività coinvolte",
        "% extra su totale progetto",
    ]

    for c in money_cols:
        cost_print[c] = cost_print[c].apply(euro_it)

    for c in pct_cols:
        cost_print[c] = cost_print[c].apply(pct_it)

    display(cost_print)


# =========================
# DETAIL: DIRECT RECOVERY
# =========================

if ENABLE_RECOVERY_RUN and not recovery_plan_df.empty:
    print("\n===== DETTAGLIO COSTI - RECOVERY DIRETTA =====")

    cols_direct = [
        "task_id",
        "full_name",
        "Baseline multiplier",
        "Recovery multiplier",
        "Durata baseline",
        "Durata recovery",
        "Ore recuperate",
        "Costo attività",
        "Costo extra totale",
        "% costo extra totale",
        "Costo per ora recuperata"
    ]

    df_print = recovery_plan_df[cols_direct].copy()

    df_print["Costo attività"] = df_print["Costo attività"].apply(euro_it)
    df_print["Costo extra totale"] = df_print["Costo extra totale"].apply(euro_it)
    df_print["% costo extra totale"] = df_print["% costo extra totale"].apply(pct_it)
    df_print["Costo per ora recuperata"] = df_print["Costo per ora recuperata"].apply(euro_it)

    display(df_print)


# =========================
# DIRECT RECOVERY RESOURCE DETAILS
# =========================

if ENABLE_RECOVERY_RUN and not recovery_plan_df.empty:
    print("\n===== EXTRA RISORSE - RECOVERY DIRETTA =====")

    extra_cols = [
        "task_id",
        "full_name",
        "Baseline multiplier",
        "Recovery multiplier",
    ] + [f"Extra {r}" for r in RESOURCE_COLS]

    display(recovery_plan_df[extra_cols])


# =========================
# CHAIN RECOVERY DETAILS
# =========================

if ENABLE_RECOVERY_RUN and not recovery_chain_plan_df.empty:
    print("\n===== DETTAGLIO COSTI - RECOVERY ECONOMICA CATENA =====")

    cols_chain = [
        "task_id",
        "full_name",
        "Tipo impatto recovery",
        "Baseline multiplier",
        "Recovery multiplier",
        "Durata baseline",
        "Durata recovery",
        "Ore recuperate",
        "Costo attività",
        "Costo extra totale",
        "% costo extra totale",
        "Costo per ora recuperata"
    ]

    df_chain_print = recovery_chain_plan_df[cols_chain].copy()

    df_chain_print["Costo attività"] = df_chain_print["Costo attività"].apply(euro_it)
    df_chain_print["Costo extra totale"] = df_chain_print["Costo extra totale"].apply(euro_it)
    df_chain_print["% costo extra totale"] = df_chain_print["% costo extra totale"].apply(pct_it)
    df_chain_print["Costo per ora recuperata"] = df_chain_print["Costo per ora recuperata"].apply(euro_it)

    display(df_chain_print)


# =========================
# CHAIN RECOVERY RESOURCE DETAILS
# =========================

if ENABLE_RECOVERY_RUN and not recovery_chain_plan_df.empty:
    print("\n===== EXTRA RISORSE - RECOVERY ECONOMICA CATENA =====")

    extra_chain_cols = [
        "task_id",
        "full_name",
        "Tipo impatto recovery",
        "Baseline multiplier",
        "Recovery multiplier",
    ] + [f"Extra {r}" for r in RESOURCE_COLS]

    display(recovery_chain_plan_df[extra_chain_cols])


# =========================
# CHAIN CANDIDATES
# =========================

if ENABLE_RECOVERY_RUN and not recovery_chain_candidates_df.empty:
    print("\n===== CANDIDATE RECOVERY ECONOMICA SU CATENA =====")

    candidate_cols = [
        "task_id",
        "full_name",
        "Tipo impatto recovery",
        "Baseline multiplier",
        "Recovery multiplier",
        "Ore recuperate",
        "Costo extra totale",
        "Costo per ora recuperata",
        "Criticality"
    ]

    candidate_print = recovery_chain_candidates_df[candidate_cols].copy()
    candidate_print["Costo extra totale"] = candidate_print["Costo extra totale"].apply(euro_it)
    candidate_print["Costo per ora recuperata"] = candidate_print["Costo per ora recuperata"].apply(euro_it)

    display(candidate_print)

# =========================
# CELLA 6 - REPORT FINALE MULTILINGUA
# =========================

REPORT_LANGUAGE = "EN"   # "IT" oppure "EN"

# =========================================================
# LABELS
# =========================================================

LABELS = {

    "IT": {

        "scenario_comparison": "===== CONFRONTO SCENARI =====",
        "cost_summary": "===== RIEPILOGO COSTI RECOVERY =====",
        "direct_detail": "===== DETTAGLIO COSTI - RECOVERY DIRETTA =====",
        "direct_resources": "===== RISORSE EXTRA - RECOVERY DIRETTA =====",
        "chain_detail": "===== DETTAGLIO COSTI - RECOVERY ECONOMICA SU CATENA =====",
        "chain_resources": "===== RISORSE EXTRA - RECOVERY ECONOMICA SU CATENA =====",
        "chain_candidates": "===== CANDIDATE RECOVERY ECONOMICA SU CATENA =====",
        "no_cost": "Nessun costo recovery da stampare.",
        "no_recovery": "Recovery non eseguita perché non c'è ritardo finale.",
    },

    "EN": {

        "scenario_comparison": "===== SCENARIO COMPARISON =====",
        "cost_summary": "===== RECOVERY COST SUMMARY =====",
        "direct_detail": "===== DIRECT RECOVERY COST DETAILS =====",
        "direct_resources": "===== EXTRA RESOURCES - DIRECT RECOVERY =====",
        "chain_detail": "===== COST-OPTIMIZED CHAIN RECOVERY DETAILS =====",
        "chain_resources": "===== EXTRA RESOURCES - CHAIN RECOVERY =====",
        "chain_candidates": "===== CHAIN RECOVERY CANDIDATES =====",
        "no_cost": "No recovery cost to display.",
        "no_recovery": "Recovery was not executed because there is no final delay.",
    }
}

# =========================================================
# COLUMN TRANSLATIONS
# =========================================================

COLUMN_TRANSLATIONS = {

    "IT": {

        "Scenario": "Scenario",
        "Fine progetto (ora assoluta)": "Fine progetto (ora assoluta)",
        "Ritardo vs baseline (h)": "Ritardo vs baseline (h)",
        "Ritardo vs baseline (gg lav)": "Ritardo vs baseline (gg lav)",

        "Costo totale baseline progetto": "Costo totale baseline progetto",
        "Costo attività coinvolte": "Costo attività coinvolte",
        "Costo extra totale recovery": "Costo extra totale recovery",
        "Costo totale progetto con recovery": "Costo totale progetto con recovery",
        "% extra su attività coinvolte": "% extra su attività coinvolte",
        "% extra su totale progetto": "% extra su totale progetto",

        "task_id": "ID task",
        "full_name": "Nome attività",

        "Baseline multiplier": "Moltiplicatore baseline",
        "Recovery multiplier": "Moltiplicatore recovery",

        "Durata baseline": "Durata baseline",
        "Durata recovery": "Durata recovery",
        "Ore recuperate": "Ore recuperate",

        "Costo attività": "Costo attività",
        "Costo extra totale": "Costo extra totale",
        "% costo extra totale": "% costo extra totale",
        "Costo per ora recuperata": "Costo per ora recuperata",

        "Tipo impatto recovery": "Tipo impatto recovery",
        "Regola macchinari": "Regola macchinari",

        "Criticality": "Criticality",

        "Extra Operai Liv.1": "Extra Operai Liv.1",
        "Extra Operai Liv.2": "Extra Operai Liv.2",
        "Extra Operai Liv.3": "Extra Operai Liv.3",

        "Extra Gru": "Extra Gru",
        "Extra Pompa Calcestruzzo": "Extra Pompa Calcestruzzo",
        "Extra Escavatore": "Extra Escavatore",
        "Extra Autocarro": "Extra Autocarro",
    },

    "EN": {

        "Scenario": "Scenario",
        "Fine progetto (ora assoluta)": "Project finish (absolute hour)",
        "Ritardo vs baseline (h)": "Delay vs baseline (h)",
        "Ritardo vs baseline (gg lav)": "Delay vs baseline (work days)",

        "Costo totale baseline progetto": "Baseline total project cost",
        "Costo attività coinvolte": "Impacted activities cost",
        "Costo extra totale recovery": "Total recovery extra cost",
        "Costo totale progetto con recovery": "Project cost with recovery",
        "% extra su attività coinvolte": "% extra on impacted activities",
        "% extra su totale progetto": "% extra on total project",

        "task_id": "Task ID",
        "full_name": "Activity name",

        "Baseline multiplier": "Baseline multiplier",
        "Recovery multiplier": "Recovery multiplier",

        "Durata baseline": "Baseline duration",
        "Durata recovery": "Recovery duration",
        "Ore recuperate": "Recovered hours",

        "Costo attività": "Activity cost",
        "Costo extra totale": "Total extra cost",
        "% costo extra totale": "% total extra cost",
        "Costo per ora recuperata": "Cost per recovered hour",

        "Tipo impatto recovery": "Recovery impact type",
        "Regola macchinari": "Machinery rule",

        "Criticality": "Criticality",

        "Extra Operai Liv.1": "Extra Workers Lv.1",
        "Extra Operai Liv.2": "Extra Workers Lv.2",
        "Extra Operai Liv.3": "Extra Workers Lv.3",

        "Extra Gru": "Extra Crane",
        "Extra Pompa Calcestruzzo": "Extra Concrete Pump",
        "Extra Escavatore": "Extra Excavator",
        "Extra Autocarro": "Extra Truck",
    }
}

# =========================================================
# VALUE TRANSLATIONS
# =========================================================

VALUE_TRANSLATIONS = {

    "IT": {

        "Baseline": "Baseline",

        "Con imprevisti - senza recovery":
            "Con imprevisti - senza recovery",

        "Con imprevisti + recovery diretta":
            "Con imprevisti + recovery diretta",

        "Con imprevisti + recovery economica catena":
            "Con imprevisti + recovery economica catena",

        "Recovery diretta":
            "Recovery diretta",

        "Recovery economica catena":
            "Recovery economica catena",

        "Diretta":
            "Diretta",

        "Indiretta":
            "Indiretta",

        "always":
            "sempre",

        "after_first_extra_team":
            "dopo prima squadra extra",
    },

    "EN": {

        "Baseline": "Baseline",

        "Con imprevisti - senza recovery":
            "With risks - no recovery",

        "Con imprevisti + recovery diretta":
            "With risks + direct recovery",

        "Con imprevisti + recovery economica catena":
            "With risks + cost-optimized chain recovery",

        "Recovery diretta":
            "Direct recovery",

        "Recovery economica catena":
            "Cost-optimized chain recovery",

        "Diretta":
            "Direct",

        "Indiretta":
            "Indirect",

        "always":
            "always",

        "after_first_extra_team":
            "after first extra team",
    }
}

L = LABELS[REPORT_LANGUAGE]

# =========================================================
# FORMAT FUNCTIONS
# =========================================================

def euro_fmt(x):

    try:
        return f"€ {x:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")
    except:
        return x

def pct_fmt(x):

    try:
        return f"{x:.2%}"
    except:
        return x

# =========================================================
# TRANSLATION FUNCTION
# =========================================================

def translate_df(df):

    out = df.copy()

    # translate columns
    col_trans = COLUMN_TRANSLATIONS[REPORT_LANGUAGE]
    out = out.rename(columns=col_trans)

    # translate values
    value_trans = VALUE_TRANSLATIONS[REPORT_LANGUAGE]

    for col in out.columns:

        if out[col].dtype == object:

            out[col] = out[col].replace(value_trans)

    return out

# =========================================================
# FORMAT MONEY / PERCENT TABLE
# =========================================================

def format_money_pct_table(df):

    out = df.copy()

    for c in out.columns:

        if "Costo" in c or "Cost" in c:
            out[c] = out[c].apply(euro_fmt)

        if "%" in c:
            out[c] = out[c].apply(pct_fmt)

    return out

# =========================================================
# SCENARIO COMPARISON
# =========================================================

print(L["scenario_comparison"])

display(
    translate_df(comparison_df)
)

# =========================================================
# COST SUMMARY
# =========================================================

print("\n" + L["cost_summary"])

if cost_summary_df.empty:

    print(L["no_cost"])

else:

    display(
        translate_df(
            format_money_pct_table(cost_summary_df)
        )
    )

# =========================================================
# DIRECT RECOVERY
# =========================================================

if ENABLE_RECOVERY_RUN and not recovery_plan_df.empty:

    print("\n" + L["direct_detail"])

    direct_cols = [
        "task_id",
        "full_name",
        "Baseline multiplier",
        "Recovery multiplier",
        "Durata baseline",
        "Durata recovery",
        "Ore recuperate",
        "Costo attività",
        "Costo extra totale",
        "% costo extra totale",
        "Costo per ora recuperata",
    ]

    display(
        translate_df(
            format_money_pct_table(
                recovery_plan_df[direct_cols]
            )
        )
    )

    print("\n" + L["direct_resources"])

    direct_resource_cols = [
        "task_id",
        "full_name",
        "Baseline multiplier",
        "Recovery multiplier",
    ] + [f"Extra {r}" for r in RESOURCE_COLS]

    display(
        translate_df(
            recovery_plan_df[direct_resource_cols]
        )
    )

# =========================================================
# CHAIN RECOVERY
# =========================================================

if ENABLE_RECOVERY_RUN and not recovery_chain_plan_df.empty:

    print("\n" + L["chain_detail"])

    chain_cols = [
        "task_id",
        "full_name",
        "Tipo impatto recovery",
        "Regola macchinari",
        "Baseline multiplier",
        "Recovery multiplier",
        "Durata baseline",
        "Durata recovery",
        "Ore recuperate",
        "Costo attività",
        "Costo extra totale",
        "% costo extra totale",
        "Costo per ora recuperata",
    ]

    display(
        translate_df(
            format_money_pct_table(
                recovery_chain_plan_df[chain_cols]
            )
        )
    )

    print("\n" + L["chain_resources"])

    chain_resource_cols = [
        "task_id",
        "full_name",
        "Tipo impatto recovery",
        "Baseline multiplier",
        "Recovery multiplier",
    ] + [f"Extra {r}" for r in RESOURCE_COLS]

    display(
        translate_df(
            recovery_chain_plan_df[chain_resource_cols]
        )
    )

# =========================================================
# CHAIN CANDIDATES
# =========================================================

if ENABLE_RECOVERY_RUN and not recovery_chain_candidates_df.empty:

    print("\n" + L["chain_candidates"])

    candidate_cols = [
        "task_id",
        "full_name",
        "Tipo impatto recovery",
        "Regola macchinari",
        "Baseline multiplier",
        "Recovery multiplier",
        "Ore recuperate",
        "Costo extra totale",
        "Costo per ora recuperata",
        "Criticality",
    ]

    display(
        translate_df(
            format_money_pct_table(
                recovery_chain_candidates_df[candidate_cols]
            )
        )
    )

# =========================================================
# NO RECOVERY
# =========================================================

if not ENABLE_RECOVERY_RUN:

    print("\n" + L["no_recovery"])